# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: ci
on:
  push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        node-version: [24.x, 26.x]
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2025, macos-15, macos-26]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
      - if: runner.os == 'Linux'
        run: >
          sudo add-apt-repository ppa:kisak/turtle &&
          sudo apt update &&
          sudo apt-get install -y build-essential libgl1-mesa-dri libglapi-mesa libglew-dev libglu1-mesa-dev libosmesa6 libxi-dev mesa-utils pkg-config
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run rebuild
      - if: runner.os == 'Linux'
        run: xvfb-run glxinfo
      - if: runner.os == 'Linux'
        run: xvfb-run npm test
      - if: runner.os != 'Linux'
        run: npm test
